UoaWDCC/nzpmc-exam-portal

resolvers/index.js, resolvers/question.js, resolvers/quizzes.js, resolvers/user.js, scalars/datetime.js, schemas/schema.graphql
**Issue**
Frontend cannot test GraphQL schema 
**Solution**
Created 'studded' resolvers for the current schema 
**Risk**
low-risk
**Reviewers**
CZ and Will
=> [NZPMC-006] Studding resolvers 

.dockerignore, .env-template, .eslintrc.json, .gitignore, Dockerfile, __tests__/controllers/user.test.js, babel.config.js, controllers/user.js, index.js, jest.config.js, models/index.js, models/option.js, models/question.js, models/quiz.js, models/user.js, models/userQuiz.js, models/userQuizAnswer.js, package-lock.json, package.json, resolvers/question.js, resolvers/quizzes.js, resolvers/user.js, scalars/datetime.js, schemas/objects.graphql, stud.js, utils/errors.js, utils/firebase.js
**Issue**
Firestore not setup
**Solution**
Add firestore, fake data, etc.
**Risk**
Fireo sucks but it's the only one that supports JS
**Reviewers**
=> [NZPMC-006] Setup firestore

README.md
**Issue**
New users don't know how to get started
**Solution**
Created instructions in a README
**Risk**
Very low 
**Reviewers**
CZ, Will
=> [NZPMC-22] Write README docs for backend

controllers/option.js, controllers/question.js, controllers/userQuizQuestion.js, resolvers/options.js
**Issue**
userQuzz query is not fetching the correct question with a specific id due to a bug in the Fireo plugin
**Solution**
using combined key instead of the given notation (workaround)
**Risk**
might need to be changed back to proper syntax when Fireo fix the bug
**Reviewers**
=> Nzpmc 029/fixing question endpoints

resolvers/index.js, resolvers/time.js, schemas/schema.graphql
**Issue**
Need to be able to to calculate time remaining in quiz.
**Solution**
Added a new query to the schema and implemented a resolver that simply returns new Date().
**Discussion**
We decided to do this instead of making a database query and returning the remaining time because we thought two graphql queries would be more performant than two database queries.
Note: recreated from current master to make merge easier
**Risk**
Low risk.
**Reviewers**
CZ, Will
=> [NZPMC-026] Create currentTime query

controllers/option.js, controllers/userQuizQuestion.js, resolvers/userQuizzes.js, schemas/input.graphql
**Issue**
userAnswers are not correctly stored and returned when using the userQuiz query
**Solution**
The issue was partially due to the same Fireo bug as the previous PR, fixed the same way.
If the user selects the correct answer, the query can not find it as it is not stored in the question. Thus, a search in the list of the correct answers was added.
**Risk**
None
**Reviewers**
@scorpionknifes @Kingston802
=> [NZPMC-037] Fixing userAnswer Bug

controllers/index.js, controllers/userQuiz.js, controllers/userQuizQuestion.js, resolvers/quizzes.js, resolvers/userQuizzes.js, schemas/input.graphql, schemas/mutations.graphql, utils/errors.js
**Issue**
Needs to calculate and set score in firebase
**Solution**
Created submitUserQuizQuestions(), setUserQuizScore()
**Discussion**
Unsure about how I implemented the update in setUserQuizScore, I tried to use the .update method but I couldn't make it work because the method didn't exist on the UserQuiz object (because it was 'packed'?). Would appreciate some review and then I'll refactor. 
Additionally, the Timestamp object is not the one in the firebase docs, it doesn't have the toDate() method but the model requires a date object hence what you see in the code. 
**Risk**
Low risk
**Reviewers**
Will, CZ
=> [NZPMC-013] Implement Submission Mutation

createAdminScript.js, resolvers/options.js, resolvers/questions.js, resolvers/quizzes.js, resolvers/time.js, resolvers/userQuizzes.js, resolvers/users.js, utils/errors.js, utils/firebase.js
**Issue**
Admin no auth
**Solution**
Add auth
**Risk**
Not tested
**Reviewers**
=> [NZPMC-043] Firebase auth admin verification

resolvers/time.js
**Issue**
I used the wrong context
**Solution**
Change context to ctx
**Reviewers**
Will, CZ
=> fixed bug in time resolver

.github/cloud_run_build_deploy.yaml, index.js
**Issue**
Application backend not deployed
**Solution**
Set up CD using GitHub action to build and deploy backend to Google Cloud Run
**Risk**
None
**Reviewers**
=> [NZPMC-039] Setup continuous deployment for backend

resolvers/userQuizzes.js
**Issue**
A student should not be able to submit after the quiz have finished
**Solution**
Compare the current time with the quiz end time + 60s.
Is this all that is necessary? 
**Risk**
Low risk 
**Reviewers**
Will, CZ
=> [NZPMC-045] Add time check to submit query

controllers/userQuizQuestion.js, index.js, models/userQuizQuestion.js, resolvers/userQuizzes.js, schemas/input.graphql, schemas/mutations.graphql, schemas/objects.graphql
**Issue**
Add flags to userQuizQuestions
Add stuff to stuff
Add method to remove userQuizAnswer e.g set the id to "" empty string (not null)
**Solution**
Add flag field to query, mutation, model (backwards compatible if flag is not set defaults to false)
Add method to deselect userQuizAnswer
- if id is set to empty string set the model to null
- if id is set to null nothing will be changed (e.g mutation default behaviour)
**Risk**
- Risk is frontend schema not up to date
- New fields are nullable so should be ok unless someone fked up.
**Reviewers**
Random list of people
@Will-ZYS 
@scorpionknifes
=> Adding flag to userquizquestion

.github/dependabot.yml
**Issue**
My dependencies are too old, and security vulnerable 
**Solution**
Add dependabot daily to remind me how old our dependencies are 
**Risk**
Giving will extra work
**Reviewers**
Random list of people
@Will-ZYS 
@scorpionknifes 
@matthewaptaylor 
@lanxdrey19 
@Kingston802
=> Add Dependabot Config yml

index.js, package-lock.json, package.json
**Issue**
Apollo V3 is out. POG ME
**Solution**
Update old dependencies and update server to v3 XD
**Risk**
Should work unless there is a bug due to dependency upgrade
**Reviewers**
Random LIST OF PEOPLE @Will-ZYS @Will-ZYS @Will-ZYS
=> Update to Apollo server v3

controllers/userQuizQuestion.js, resolvers/userQuizzes.js
**Issue**
Not returning question.
**Solution**
returns question
**Risk**
**Reviewers**
@lanxdrey19
=> Fix by return question

controllers/userQuizQuestion.js, index.js, resolvers/userQuizzes.js
**Issue**
Fix options query cause questionObj is missing on return
**Solution**
add questionObj to return so resolver works
**Risk**
**Reviewers**
=> Add questionObj to return for resolver

.env-template, controllers/userQuiz.js, controllers/userQuizQuestion.js, package-lock.json, package.json, resolvers/userQuizzes.js, resolvers/users.js, schemas/input.graphql, utils/firebase.js
Co-authored-by: ZHENK <chengzhenyang@gmail.com>
**Issue**
user-register mutation not implemented
**Solution**
user register mutation now implemented
n/a
**Risk**
none known
**Reviewers**
@scorpionknifes 
@Kingston802 
@Will-ZYS
=> Implemented user-register mutation

.github/workflows./autoapprove.yml
**Issue**
WHY DO WE STILL HAVE THIS 2 PEOPLE REVIEW LIMIT...
**Solution**
Approve dependabot using a bot as 2nd approve.
**Risk**
Will go angry
**Reviewers**
=> Add auto approve for dependabot

controllers/userQuizQuestion.js, resolvers/userQuizzes.js
Co-authored-by: ZHENK <chengzhenyang@gmail.com>
**Issue**
Fix deselection/selection mutation bug
**Solution**
fixed edit user quiz question in userquizquestion controller
**Risk**
None known
**Reviewers**
@Will-ZYS 
@scorpionknifes
=> [NZPMC-068] Fix option deselection mutation

Dockerfile, package.json
**Issue**
No idea why backend isn't deploying
**Solution**
Try commit something with new settings and debug further
**Risk**
It doesn't work and we do 1 extra commit
**Reviewers**
=> [NZPMC-082] Fix backend deployment

.env-template, index.js, package-lock.json, package.json, resolvers/image.js, resolvers/index.js, schemas/input.graphql, schemas/mutations.graphql, schemas/objects.graphql, schemas/schema.graphql, utils/cloudstorage.js, utils/firebase.js
**Issue**
Setup bucket for google cloud storage
**Solution**
Updated schema
Mutation: 
```
image(input: ImageUploadInput!): Image
```
Query:
```
image(questionID: ID!): [Image]!
```
**Risk**
**Reviewers**
=> [NZPMC-049] Setup images hosting on google cloud storage

resolvers/quizzes.js, schemas/objects.graphql, schemas/schema.graphql
**Issue**
GraphQL was not sending everything needed to display quiz admin.
**Solution**
Add data.
**Reviewers**
=> Nzpmc 063/connect quizadmin page

schemas/input.graphql, schemas/objects.graphql, schemas/schema.graphql
**Issue**
Needed pagination for users
=> Schema change

controllers/index.js, controllers/user.js, resolvers/users.js, schemas/schema.graphql
**Issue**
Add search and pagination for users on backend
**Solution**
Add search and pagination for users on backend
**Risk**
Explode
**Reviewers**
=> [NZPMC-084] Add search pagination users

controllers/question.js
**Issue**
Could not edit questions when no answer was assigned, could not add a question
**Solution**
Fixed incomplete refactoring in addQuestion, fixed undefined answer bug
**Risk**
None
**Reviewers**
=> Nzpmc 064/connect quizadminquestion

package-lock.json, src/controllers/index.ts, src/controllers/question.ts, src/controllers/quiz.ts, src/resolvers/mutationResolvers.ts, src/resolvers/resolvers-types.ts, src/schemas/mutations.graphql
**Issue**
swap mutation to swap order of questions
**Solution**
implement the swap query
**Risk**
It maybe doesn't work
**Reviewers**
=> [NZPMC-91] Add swap mutation

src/controllers/question.ts, src/resolvers/mutationResolvers.ts
**Issue**
Fixes previous issue where options weren't swapped when questions were swapped
**Risk**
* Worse case scenario questions are bugged in database
=> [NZPMC-91] Fixed option of questions when swapped

src/controllers/index.ts, src/controllers/userQuizQuestion.ts, src/resolvers/userQuizQuestionResolvers.ts
**Issue**
submit mutation not working
updated user selected doesn't return the right answer
**Solution**
Fix submit mutation
Fix user selected return from query user answers
**Risk**
**Reviewers**
@scorpionknifes
=> [NZPMC-95][NZPMC-96] Fix calculating score and fix user selected answer not returning

src/resolvers/mutationResolvers.ts, src/resolvers/resolvers-types.ts, src/schemas/input.graphql, src/schemas/mutations.graphql
**Issue**
Needed schema for reordering questions
**Solution**
Added schema to graphql backend
=> [NZPMC-102] Implement question reordering schema change

src/controllers/user.ts, src/resolvers/queryResolvers.ts, src/resolvers/resolvers-types.ts, src/schemas/schema.graphql, src/utils/firebase.ts
**Issue**
Currently, user story for nzpmc-060 does not work on the typescript branch
**Solution**
Make changes to typescript branch to support changes made in the frontend for user story nzpmc-060
**Risk**
n/a
**Reviewers**
=> implement backend changes for NZPMC-060

src/controllers/user.ts
**Issue**
Search functionality was not working for the Users page in the Admin section
**Solution**
Minor mistake that was not returning the users that matched the search term is now fixed.
**Reviewers**
=> [NZPMC-060] Minor fixes to search function

src/controllers/index.ts, src/controllers/option.ts, src/resolvers/mutationResolvers.ts, src/resolvers/resolvers-types.ts, src/schemas/mutations.graphql
**Issue**
Lack of mutations to delete answer options.
**Solution**
Added the respective mutations to carry out the operation.
**Reviewers**
=> nzpmc-093/Delete-answers-and-questions

src/controllers/userQuiz.ts, src/controllers/userQuizQuestion.ts, src/mappers/userQuizMapper.ts, src/resolvers/custom/userQuizModel.ts, src/resolvers/userQuizResolvers.ts, src/utils/errors.ts
**Issue**
Check if a quiz expired and does not return questions or allow changing answers
**Solution**
check and use custom model to stop resolver 
**Risk**
**Reviewers**
=> [NZPMC-099] Add expired flag on model to check if quiz expired

src/controllers/question.ts, src/controllers/quiz.ts, src/controllers/userQuizQuestion.ts, src/models/quiz.ts, src/resolvers/mutationResolvers.ts, src/resolvers/resolvers-types.ts, src/schemas/input.graphql, src/schemas/mutations.graphql
**Issue**
Need to implement question reordering based on an array of question IDs
**Solution**
Modified existing services and added mutation to allow for question reordering
=> [NZPMC-103] Implement question reordering with order array

.github/workflows/lint.yml, README.md, exam-portal-frontend/.env-template, exam-portal-frontend/README.md, exam-portal-frontend/package.json
**Issue**
Improve clarity in setting up codebase
**Solution**
Specify .env-template file
=> doc: add project setup

README.md
**Issue**
Names not filled in on README.md
**Solution**
Add name
**Risk**
**Reviewers**
John (TL), Nate (PM)
=> doc: add name to readme

README.md
**Issue**
Name not yet added to outer README.
**Solution**
Added name to line under heading "Team Members"
**Risk**
None
**Reviewers**
@johnchen383 
@nzkevc
=> 000_add-name-alex-kim

README.md
**Issue**
Name not added to README.md
**Solution**
Added name to README.me under 'Team Members' header
**Risk**
None
**Reviewers**
@johnchen383 
@luorixo
=> doc: add name to read me

README.md
**Issue**
Making this cause my name isn't on the readme :)
**Solution**
I added my name cuz I should
**Risk**
I might've done an oopsie
**Reviewers**
@johnchen383 
@ardo715
=> doc: add my name to readme

client/src/components/app/exams/index.vue, client/src/main.ts
**Issue**
The components weren't displaying as well as errors talking to server
**Solution**
- I removed the ApolloQuery component and did the fetching inside the script tag using the "apollo" option as I couldn't find a way to get the component to work
- I added the handler for the user change so that authentication works properly
- I added the skeleton loader from the labs module of vuetify
- I pruned incompatible vuetify components from the topbar so the page would somewhat render
Note that the styling has not been fixed yet, however this could be fixed by copying over the old configs
**Risk**
- Will require refactoring of topbar
- Using the apollo option may not be the same as using the apolloquery component
=> Small fixes for migration

client/src/components/auth/index.vue
**Issue**
Missing language causing crashes
Closes #[Replace with ticket number]
**Solution**
fix: add lang='ts' to auth/index.vue
**Risk**
**Reviewers**
=> fix: add lang='ts' to auth/index.vue

.github/ISSUE_TEMPLATE/design-template.md
**Issue**
Issue template was not complete.
Closes #283 
**Solution**
Changed line in DoD about getting approval from nzpmc marketing.
**Risk**
None
**Reviewers**
@johnchen383 
@else861
=> 283 Issue Templates

.github/ISSUE_TEMPLATE/admin-template.md, .github/ISSUE_TEMPLATE/design-template.md, .github/ISSUE_TEMPLATE/dev-template.md, .github/pull_request_template.md
**Issue**
PR/issue templates had redundant/confusing info.
**Solution**
Removed redundant info and clarified bits.
**Risk**
None
**Reviewers**
@johnchen383 
@alexmingikim
=> Simplified issue and PR templates

client/package.json, client/src/components/app/DisplayText.vue, client/src/components/app/exam/Question/Options.vue, client/src/components/app/exam/Question/index.vue, client/src/components/app/exam/Sidebar.vue, client/src/components/app/exam/SidebarLink.vue, client/src/components/app/exam/Topbar.vue, client/src/components/app/exam/TopbarLoader.vue, client/src/components/app/exam/TopbarTimer.vue, client/src/components/app/exam/index.vue, client/src/plugins/vuetify.js, client/src/styles/_variables.scss, client/src/styles/globals.scss, yarn.lock
**Issue**
Exam layout was nonexistent.
Closes #352
**Solution**
Add back the broken layout from before the Vue 3 migration and add some preliminary styling in preparation for next tickets.
**Risks**
Only Benson has touched this, uncertain.
**Reviewers**
@johnchen383 
@luorixo
=> 352 exam layout

client/src/components/app/exam/Question/index.vue, client/src/components/app/exam/index.vue, client/src/components/app/exams/List.vue, client/src/components/app/exams/index.vue, client/src/gql/fragments/userQuiz.ts, client/src/gql/queries/userQuiz.ts, common/src/models/custom/userQuizModel.ts, common/src/models/resolvers-types.ts, service/src/mappers/userQuizMapper.ts, service/src/schemas/objects.graphql
Fix various issues including loading userquiz by quiz id + loading in questions at initiation to remove loading time between questions.
=> Load UserQuiz On Load

client/src/components/app/exam/Sidebar.vue, client/src/components/app/exam/SidebarLink.vue, client/src/components/app/exams/List.vue, client/src/components/app/exams/index.vue, service/src/controllers/userQuiz.ts, service/src/resolvers/queryResolvers.ts
**Issue**
Closes #357 
**Solution**
The navbar has been implemented according to the figma design. Functionally it is correct, with it being blocked by issues: #359 and #361 
Functionality of the submit button, which is located in the navbar, is part of #361 therefore its implementation has been left incomplete in this PR.
**Risks**
Functionality such as flagging and answering a question has not been implemented yet so integration is not tested
**Reviewers**
=> 357 exam navbar

client/src/components/app/exam/Question/FlagButton.vue, client/src/components/app/exam/Question/index.vue, client/src/components/app/exam/Sidebar.vue, client/src/components/app/exams/InfoCard.vue, client/src/components/app/exams/List.vue, client/src/components/app/exams/index.vue, client/src/gql/fragments/userInfo.ts, client/src/gql/mutations/userQuiz.ts, client/src/gql/queries/userQuiz.ts, common/src/models/custom/userQuizModel.ts, common/src/models/resolvers-types.ts, service/src/controllers/userQuiz.ts, service/src/controllers/userQuizQuestion.ts, service/src/mappers/userQuizMapper.ts, service/src/models/userQuiz.ts, service/src/resolvers/mutationResolvers.ts, service/src/schemas/objects.graphql
**Issue**
Continuation of #361 
**Solution**
Functional flag, next, and submit buttons
**Risks**
Slow when talking to firebase, user not notified of status
**Reviewers**
everyone
=> feat: got working buttons again

client/src/components/app/admin/QuizManagement.vue, client/src/components/app/admin/UserManagement.vue, client/src/components/app/admin/index.vue, client/src/styles/_variables.scss
**Issue**
Partially closes #353 
**Solution**
Layout done :)
**Risks**
Old buttons still need to be removed :/
**Reviewers**
=> 353 admin layout

client/src/components/app/Topbar.vue, client/src/components/app/exams/index.vue, client/src/main.ts, client/src/stores/main.ts, client/src/utils/formattingMixin.ts, service/src/controllers/user.ts
**Issue**
Closes #380 
**Solution**
I have displayed the user's name on the exams page as well as when they click the user icon on the navbar.
Additionally, I have corrected the contact email.
**Risks**
No risk
**Reviewers**
=> 380 app login confirmation

client/src/components/app/admin/QuizManagement.vue, client/src/gql/mutations/quiz.ts, client/src/gql/mutations/userQuiz.ts, client/src/gql/queries/quiz.ts, client/src/utils/csv_parser.ts, client/src/utils/quizManagement.ts, common/src/models/custom/quizModel.ts, service/src/controllers/quiz.ts, service/src/controllers/user.ts, service/src/controllers/userQuiz.ts, service/src/controllers/userQuizQuestion.ts, service/src/resolvers/mutationResolvers.ts, service/src/schemas/input.graphql
**Issue**
Closes #382 
**Solution**
Ticked off all the acceptance criteria for ticket #382.
Can create new exam
Selecting, Loading, Editing and saving exam info into DB
Saves directly to db on edit, with debounce period of 300ms 
Can download csv of userquizzes
**Note**: enrollment accepts any csv that contains a valid email or id
The csv is accepted by enrollment
Enrollment also works with the default format & rejects invalid users
**Risks**
- Make sure that all data types match up to whats in the database, have already changed to open/close time and renamed all docs
**Reviewers**
=> feat: :sparkles: implement quiz management functionality (#382)

client/src/components/app/admin/QuizManagement.vue, client/src/components/app/admin/UserManagement.vue, client/src/utils/quizManagement.ts, client/src/utils/userManagement.ts, common/src/models/custom/index.ts, service/src/controllers/userQuiz.ts
**Issue**
No warning when enrolling, adding, or deleting users
Closes #386 
**Solution**
Added confirmation warnings to enrolling to a quiz, adding / deleting users to database
**Risks**
none =) (hopefully)
**Reviewers**
@johnchen383 
@luorixo
=> 386 admin warnings

client/src/components/app/admin/QuizManagement.vue, client/src/components/app/admin/UserManagement.vue, client/src/utils/quizManagement.ts, service/src/controllers/user.ts, service/src/resolvers/mutationResolvers.ts, service/src/utils/firebase.ts
**Issue**
Closes #393 
Before if the users didn't exist in the db/auth before creation they would just be ignored. 
**Solution**
The users are now created in both the db/auth on enrollment
**Risks**
Bug where if you have duplicate emails and no existing userquiz for the user associated with that email when enrolling (should not happen from the downloaded csv, but input should be sanitised), multiple userquizzes are created for the first user with that email as calls are asynchronous and there is no check for existing quizzes that can happen during that time
**Reviewers**
=> feat: ✨ create user in auth and db if doesnt exist on enrollment

client/src/components/app/admin/QuizManagement.vue, client/src/components/app/admin/UserManagement.vue, client/src/components/app/exam/index.vue, client/src/utils/quizManagement.ts, service/src/controllers/userQuiz.ts, service/src/resolvers/mutationResolvers.ts
**Issue**
There were some minor linting issues that had made their way to main.
**Solution**
Ran the linter. lint:f didn't work so I manually went through to (try to) fix them!
**Risks**
I'm making changes in the dark for a lot of these (and had to alter the logic for a few of them) so please make extra certain to double-check everything! I think it works but have no way to test them cause a lot of this is error handling code.
**Reviewers**
@ardo715 
@bcho892
=> Hot: fix linting

client/src/components/app/admin/QuizManagement.vue, client/src/components/app/exam/Question/index.vue, client/src/utils/quizManagement.ts, service/src/controllers/userQuiz.ts
**Issue**
Deleting an exam did not delete associated user quizzes
Closes #444 
**Solution**
Implemented cascading deletion upon deletion of an exam
It works
**Risks**
might delete all exams idk
**Reviewers**
@else861 @Oculux314
=> #445 cascading deletion on exam delete

client/src/components/app/DisplayText.vue, client/src/components/app/admin/QuizManagement.vue, client/src/components/app/admin/UserManagement.vue, client/src/components/app/exam/Question/FlagButton.vue, client/src/components/app/exam/Question/Options.vue, client/src/components/app/exam/Question/index.vue, client/src/components/app/exam/Sidebar.vue, client/src/components/app/exam/SidebarLink.vue, client/src/components/app/exam/Topbar.vue, client/src/components/app/exam/TopbarLoader.vue, client/src/components/app/exam/index.vue, client/src/gql/mutations/quizQuestion.ts, client/src/gql/queries/quiz.ts, client/src/utils/quizEditingMixin.ts, service/src/controllers/question.ts, service/src/controllers/quiz.ts, service/src/resolvers/mutationResolvers.ts, service/src/schemas/input.graphql, service/src/schemas/mutations.graphql, service/src/schemas/objects.graphql
**Issue**
Closes #411, #424 
We need a question editor and way for admins to manage the exam. I have created both which function without *major* bugs.
**Solution**
Main functionality 
As you can see we can:
- Preview the exam questions
- Edit each field
- choose the correct answer
I have also implemented deletion which will be very useful later
>btw normal exam should still work fine
Users/admins should NOT be able to accidentally access this page as all features are guarded by the url queries as well as the admin check
**Risks**
1. there is **NO upload image field**
- Why? I just thought it would be a pain in the @$5 to get working (need to upload to a file hosting service, download url, update document) and they've been directly pasting the image url using MARKDOWN format so I dont see …
=> feat: :sparkles: implement question editor

client/src/components/app/DisplayText.vue
**Issue**
Small bug where latex didnt work on exam editor
=> Hotfix latex

client/src/components/app/admin/QuizManagement.vue, client/src/utils/quizManagement.ts, client/src/utils/userManagement.ts
**Issue**
Removed popup that edit questions was not yet implemented
Closes #460 
**Solution**
Removed code that showed the popup
**Risks**
None
**Reviewers**
@Oculux314 
@luorixo 
@nzkevc
=> 460 remove old question editor popup

client/src/utils/quizManagement.ts, client/src/utils/time_stamp.ts, client/src/utils/userManagement.ts
**Issue**
The names of the downloaded csv files were not meaningful. 
Closes #426
**Solution**
Renamed csv files as described on project board. 
**Risks**
None. 
**Reviewers**
@Oculux314 
@nzkevc
=> 426 csv names

client/src/components/app/Topbar.vue, client/src/components/app/admin/QuizManagement.vue, client/src/components/app/admin/grading/index.vue, client/src/components/app/admin/index.vue, client/src/components/app/exam/Sidebar.vue, client/src/components/app/exam/index.vue, client/src/components/app/exam/preExam.vue, client/src/components/app/exams/List.vue, client/src/gql/mutations/quiz.ts, client/src/gql/mutations/userQuiz.ts, client/src/gql/queries/quiz.ts, client/src/gql/queries/userQuiz.ts, client/src/main.ts, client/src/router/index.ts, common/src/models/custom/quizModel.ts, common/src/models/custom/userQuizModel.ts, service/src/controllers/index.ts, service/src/controllers/quiz.ts, service/src/controllers/userQuiz.ts, service/src/mappers/quizMapper.ts, service/src/mappers/userQuizMapper.ts, service/src/models/quiz.ts, service/src/models/userQuiz.ts, service/src/resolvers/mutationResolvers.ts, service/src/resolvers/queryResolvers.ts, service/src/schemas/input.graphql, service/src/schemas/mutations.graphql, service/src/schemas/objects.graphql
**Issue**
Closes #450 #433 
**Solution**
We need grading, so new functionality has been added on both the front and back end
**Risks**
**Reviewers**
=> feat: :sparkles: implement grading

client/src/components/app/exams/index.vue, service/src/resolvers/mutationResolvers.ts
**Issue**
Submission was very slow
**Solution**
I identified a block of code from the old submission logic which tried to make use of also grading the quiz before actually finishing the mutation
=> perf: :zap: reduce delay on submission

client/src/components/app/exams/index.vue
=> fix: :bug: dont clear localstorage

.github/workflows/deploy-dev.yml, client/src/components/app/exam/preExam.vue
**Issue**
Frontend (client) needs to be deployed.
**Solution**
Update frontend part of `deploy-dev.yml` to work with the 2023 architecture.
Also added seconds -> minutes fix for pre-exam page bug found at projects celebrations night.
**Risks**
None.
**Reviewers**
=> Deploy Frontend

.github/workflows/deploy-dev.yml
**Issue**
Backend (service) needs to be deployed.
**Solution**
Update backend part of `deploy-dev.yml` to work with the 2023 architecture.
Also fixed frontend script to use yarn not npm.
**Risks**
None.
**Reviewers**
=> Deploy Backend
